# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Fichiers XDC/Nexys4DDR_Master.xdc

# Block Designs: bd/TP2/TP2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2 || ORIG_REF_NAME==TP2}]

# IP: bd/TP2/ip/TP2_microblaze_0_0/TP2_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_0 || ORIG_REF_NAME==TP2_microblaze_0_0}]

# IP: bd/TP2/ip/TP2_dlmb_v10_0/TP2_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_dlmb_v10_0 || ORIG_REF_NAME==TP2_dlmb_v10_0}]

# IP: bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_ilmb_v10_0 || ORIG_REF_NAME==TP2_ilmb_v10_0}]

# IP: bd/TP2/ip/TP2_dlmb_bram_if_cntlr_0/TP2_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP2_dlmb_bram_if_cntlr_0}]

# IP: bd/TP2/ip/TP2_ilmb_bram_if_cntlr_0/TP2_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TP2_ilmb_bram_if_cntlr_0}]

# IP: bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_lmb_bram_0 || ORIG_REF_NAME==TP2_lmb_bram_0}]

# IP: bd/TP2/ip/TP2_microblaze_0_axi_periph_0/TP2_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_periph_0}]

# IP: bd/TP2/ip/TP2_microblaze_0_axi_intc_0/TP2_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_intc_0}]

# IP: bd/TP2/ip/TP2_microblaze_0_xlconcat_0/TP2_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==TP2_microblaze_0_xlconcat_0}]

# IP: bd/TP2/ip/TP2_mdm_1_0/TP2_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_mdm_1_0 || ORIG_REF_NAME==TP2_mdm_1_0}]

# IP: bd/TP2/ip/TP2_clk_wiz_1_0/TP2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_clk_wiz_1_0 || ORIG_REF_NAME==TP2_clk_wiz_1_0}]

# IP: bd/TP2/ip/TP2_rst_clk_wiz_1_100M_0/TP2_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TP2_rst_clk_wiz_1_100M_0}]

# IP: bd/TP2/ip/TP2_axi_gpio_0_1/TP2_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_1 || ORIG_REF_NAME==TP2_axi_gpio_0_1}]

# IP: bd/TP2/ip/TP2_axi_gpio_0_2/TP2_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_2 || ORIG_REF_NAME==TP2_axi_gpio_0_2}]

# IP: bd/TP2/ip/TP2_xbar_0/TP2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_xbar_0 || ORIG_REF_NAME==TP2_xbar_0}]

# XDC: bd/TP2/ip/TP2_microblaze_0_0/TP2_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_0 || ORIG_REF_NAME==TP2_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_microblaze_0_0/TP2_microblaze_0_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_dlmb_v10_0/TP2_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_dlmb_v10_0 || ORIG_REF_NAME==TP2_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_dlmb_v10_0/TP2_dlmb_v10_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_ilmb_v10_0 || ORIG_REF_NAME==TP2_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_ilmb_v10_0/TP2_ilmb_v10_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_dlmb_bram_if_cntlr_0/TP2_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_ilmb_bram_if_cntlr_0/TP2_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_lmb_bram_0/TP2_lmb_bram_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_microblaze_0_axi_intc_0/TP2_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_microblaze_0_axi_intc_0/TP2_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==TP2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_microblaze_0_axi_intc_0/TP2_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_mdm_1_0/TP2_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_mdm_1_0 || ORIG_REF_NAME==TP2_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_mdm_1_0/TP2_mdm_1_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_clk_wiz_1_0/TP2_clk_wiz_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_clk_wiz_1_0 || ORIG_REF_NAME==TP2_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_clk_wiz_1_0/TP2_clk_wiz_1_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_clk_wiz_1_0/TP2_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_clk_wiz_1_0 || ORIG_REF_NAME==TP2_clk_wiz_1_0}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_rst_clk_wiz_1_100M_0/TP2_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TP2_rst_clk_wiz_1_100M_0}]

# XDC: bd/TP2/ip/TP2_rst_clk_wiz_1_100M_0/TP2_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/TP2/ip/TP2_rst_clk_wiz_1_100M_0/TP2_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TP2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==TP2_rst_clk_wiz_1_100M_0}]

# XDC: bd/TP2/ip/TP2_axi_gpio_0_1/TP2_axi_gpio_0_1_ooc.xdc

# XDC: bd/TP2/ip/TP2_axi_gpio_0_1/TP2_axi_gpio_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_1 || ORIG_REF_NAME==TP2_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_axi_gpio_0_1/TP2_axi_gpio_0_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_1 || ORIG_REF_NAME==TP2_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_axi_gpio_0_2/TP2_axi_gpio_0_2_ooc.xdc

# XDC: bd/TP2/ip/TP2_axi_gpio_0_2/TP2_axi_gpio_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_2 || ORIG_REF_NAME==TP2_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_axi_gpio_0_2/TP2_axi_gpio_0_2_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TP2_axi_gpio_0_2 || ORIG_REF_NAME==TP2_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/TP2/ip/TP2_xbar_0/TP2_xbar_0_ooc.xdc

# XDC: bd/TP2/TP2_ooc.xdc
